DROP TABLE IF EXISTS "order_items";
DROP TABLE IF EXISTS "transfers";
DROP TABLE IF EXISTS "entries";
DROP TABLE IF EXISTS "orders";
DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "products";


