// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: boba_shop.sql

package db

import (
	"context"
)

const createBobaShop = `-- name: CreateBobaShop :one
INSERT INTO boba_shop (
    name
) VALUES (
    $1
) RETURNING shop_id, name
`

func (q *Queries) CreateBobaShop(ctx context.Context, name string) (BobaShop, error) {
	row := q.db.QueryRow(ctx, createBobaShop, name)
	var i BobaShop
	err := row.Scan(&i.ShopID, &i.Name)
	return i, err
}
