// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BobaShop struct {
	ShopID int64  `json:"shop_id"`
	Name   string `json:"name"`
}

type Order struct {
	OrderID   int64       `json:"order_id"`
	UserID    int64       `json:"user_id"`
	Status    pgtype.Text `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	BobaShop  pgtype.Int8 `json:"boba_shop"`
}

type OrderItem struct {
	OrderItemID int64 `json:"order_item_id"`
	OrderID     int64 `json:"order_id"`
	ProductID   int64 `json:"product_id"`
	Quantity    int32 `json:"quantity"`
}

type Personnel struct {
	BadgeNumber int64       `json:"badge_number"`
	Name        string      `json:"name"`
	Shop        int64       `json:"shop"`
	HashedPin   string      `json:"hashed_pin"`
	Email       pgtype.Text `json:"email"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Product struct {
	ProductID int64  `json:"product_id"`
	Name      string `json:"name"`
	Price     int32  `json:"price"`
}

type User struct {
	ID             int64       `json:"id"`
	Username       string      `json:"username"`
	HashedPassword string      `json:"hashed_password"`
	Name           string      `json:"name"`
	Balance        pgtype.Int8 `json:"balance"`
	CreatedAt      time.Time   `json:"created_at"`
}
