// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64       `json:"id"`
	OrderID   pgtype.Int8 `json:"order_id"`
	AccountID pgtype.Int8 `json:"account_id"`
	CreatedAt time.Time   `json:"created_at"`
}

type Item struct {
	ItemID   int64  `json:"item_id"`
	ItemName string `json:"item_name"`
	Amount   int64  `json:"amount"`
}

type Order struct {
	ID int64 `json:"id"`
}

type OrderDetail struct {
	OrderDetailID int64       `json:"order_detail_id"`
	OrderID       pgtype.Int8 `json:"order_id"`
	ItemID        pgtype.Int8 `json:"item_id"`
	Quantity      int32       `json:"quantity"`
}

type Transfer struct {
	ID            int64       `json:"id"`
	FromAccountID pgtype.Int8 `json:"from_account_id"`
	ToAccountID   pgtype.Int8 `json:"to_account_id"`
	// it must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
