// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, productID int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetOrder(ctx context.Context, orderID int64) (Order, error)
	GetOrderItem(ctx context.Context, orderID int64) (OrderItem, error)
	GetProduct(ctx context.Context, productID int64) (Product, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListOrderItem(ctx context.Context, arg ListOrderItemParams) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
